don't erase existing body classnames
PactCoffee/react-body-classname pull request #6
Opened 2017-10-08 18:01 UTC by mikhuang

I was having a problem with [reactstrap](http://reactstrap.github.io) where the `modal-open` class name it set on <body> was erased. This pull request tracks which classes have been added by ReactBodyClassname and preserves other classes set on <body>.

2017-10-16 13:38 UTC, iest requested changes
Firstly, thanks so much for opening a PR!

Secondly, apologies for the slow response. I wasn't sure if the library should support your use case — never too sure about duplicating state, and wasn't convinced it was necessary.

However, your implementation seems to work well and I _don't think_ it has any negative effects (or any potential memory leak issues for SSR which I was initially worried about).

Just a couple changes to make the code easier to understand and it's good to go ✨

2017-10-16 13:38 UTC, iest commented on test/browser.spec.js
> +  });
Could you add a test that it doesn't duplicate classnames that already exist on the body _and_ have been added by this lib? I'm thinking about SSR and want to make sure the base is covered.

2017-10-16 13:38 UTC, iest commented on index.js
> +let classNameCache = []
I think the cache should be a static property on `BodyClassName` itself — it might be useful to expose it for people to use.

2017-10-16 13:38 UTC, iest commented on index.js
> +  currentClassNames = currentClassNames.concat(newClassNames);
I'm not a huge fan of the imperative-mutation approach. A functional approach would be better imho.
Maybe something like:

```js
// Lets say we already added some
BodyClassName.addedClassNames = ['foo', 'bar', 'baz'];

var currentClassNames = splitClassName(document.body.className).filter(function(
  className
) {
  return cache.indexOf(className) !== -1;
});

var newClassNames = currentClassNames
  .concat(splitClassName(stringClassNames))
  .join(' ')
  .trim();
  
BodyClassName.addedClassNames = newClassNames;
document.body.className = newClassNames;
```

2018-04-23 09:54 UTC, iest commented
@mikhuang any progress on these changes? I'll probably close the PR soon due to inactivity if not.

Thanks!

2019-03-29 16:17 UTC, JiiB commented
@mikhuang This is exactly what I need. @iest I'm going to make a PR with mikhuang's changes and your feedback request.

2019-04-01 15:50 UTC, iest commented
Closing in favour of #8

2019-04-01 15:50 UTC, closed without merging